# Generated by Django 6.0.1 on 2026-01-17 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembers',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_groups', to='users.profile'),
        ),
        migrations.AddField(
            model_name='groups',
            name='assistant',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'assistant'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistant_groups', to='users.profile'),
        ),
        migrations.AddField(
            model_name='groups',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='groups.category'),
        ),
        migrations.AddField(
            model_name='groups',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_groups', to='users.profile'),
        ),
        migrations.AddField(
            model_name='groupmembers',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='groups.groups'),
        ),
        migrations.AddField(
            model_name='homework',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='groups.groups'),
        ),
        migrations.AddField(
            model_name='homeworksubmission',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='groups.homework'),
        ),
        migrations.AddField(
            model_name='homeworksubmission',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to='users.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmembers',
            unique_together={('group', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='homeworksubmission',
            unique_together={('homework', 'student')},
        ),
    ]
